apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      imagePullSecrets:
        - name: sitecore-docker-registry
      containers:
      - name: solr-init
        image: scr.sitecore.com/sxp/sitecore-xm1-solr-init:10.2.0-ltsc2022
        env:
        - name: SITECORE_SOLR_CONNECTION_STRING
          value: http://solr-solrcloud-common/solr
        - name: SOLR_CORE_PREFIX_NAME
          value: sumit
      restartPolicy: Never
  backoffLimit: 5